select
    {{ as_bigint('id') }} as customer_id,
    {{ as_int('year_birth') }} as year_birth,
    trim(education) as education,
    trim(marital_status) as marital_status,
    {{ as_double('income') }} as income,
    {{ as_int('kidhome') }} as kidhome,
    {{ as_int('teenhome') }} as teenhome,
    {{ as_date('dt_customer', 'd-M-yyyy') }} as customer_since_date,
    {{ as_int('recency') }} as recency_days,
    {{ as_double('mntwines') }} as amount_wines,
    {{ as_double('mntfruits') }} as amount_fruits,
    {{ as_double('mntmeatproducts') }} as amount_meat,
    {{ as_double('mntfishproducts') }} as amount_fish,
    {{ as_double('mntsweetproducts') }} as amount_sweets,
    {{ as_double('mntgoldprods') }} as amount_gold,
    {{ as_int('numdealspurchases') }} as deal_purchases,
    {{ as_int('numwebpurchases') }} as web_purchases,
    {{ as_int('numcatalogpurchases') }} as catalog_purchases,
    {{ as_int('numstorepurchases') }} as store_purchases,
    {{ as_int('numwebvisitsmonth') }} as monthly_web_visits,
    {{ as_int('acceptedcmp1') }} as accepted_campaign_1,
    {{ as_int('acceptedcmp2') }} as accepted_campaign_2,
    {{ as_int('acceptedcmp3') }} as accepted_campaign_3,
    {{ as_int('acceptedcmp4') }} as accepted_campaign_4,
    {{ as_int('acceptedcmp5') }} as accepted_campaign_5,
    {{ as_int('complain') }} as complaint_flag,
    {{ as_double('z_costcontact') }} as campaign_contact_cost,
    {{ as_double('z_revenue') }} as campaign_revenue,
    {{ as_int('response') }} as last_campaign_response_flag
from {{ source('raw_data', 'marketing_campaign') }}
