select
    {{ as_bigint('customerid') }} as customer_id,
    {{ as_boolean_flag('churn') }} as is_churned,
    {{ as_int('tenure') }} as tenure_months,
    trim(preferredlogindevice) as preferred_login_device,
    {{ as_int('citytier') }} as city_tier,
    {{ as_double('warehousetohome') }} as warehouse_to_home_km,
    trim(preferredpaymentmode) as preferred_payment_mode,
    trim(gender) as gender,
    {{ as_double('hourspendonapp') }} as hours_spent_on_app,
    {{ as_int('numberofdeviceregistered') }} as registered_device_count,
    trim(preferedordercat) as preferred_order_category,
    {{ as_int('satisfactionscore') }} as satisfaction_score,
    trim(maritalstatus) as marital_status,
    {{ as_int('numberofaddress') }} as address_count,
    {{ as_int('complain') }} as complaint_flag,
    {{ as_double('orderamounthikefromlastyear') }} as order_amount_hike_pct,
    {{ as_int('couponused') }} as coupon_used_count,
    {{ as_int('ordercount') }} as order_count,
    {{ as_int('daysincelastorder') }} as days_since_last_order,
    {{ as_double('cashbackamount') }} as cashback_amount
from {{ source('raw_data', 'e_commerce_customer_churn') }}
