cluster_name: customerdna-distributed-demo

service_placement:
  control_plane_pc:
    services:
      - airflow_api_server
      - airflow_scheduler
      - airflow_dag_processor
      - airflow_triggerer
      - airflow_init
      - airflow_postgres
      - spark_submit_client
      - pipeline_metrics_exporter
      - postgres_exporter
      - prometheus
      - grafana

  vm1:
    services:
      - kafka_broker_1
      - hdfs_datanode_1
      - spark_worker_1
      - trino_worker_1
      - cadvisor

  vm2:
    services:
      - kafka_broker_2
      - hdfs_namenode
      - hdfs_datanode_2
      - hive_metastore_postgres
      - hive_metastore
      - spark_master
      - spark_worker_2
      - spark_history_server
      - spark_thrift_server
      - trino_coordinator
      - cadvisor

  vm3:
    services:
      - kafka_broker_3
      - hdfs_datanode_3
      - spark_worker_3
      - trino_worker_2
      - cadvisor

primary_endpoints:
  kafka_bootstrap_servers:
    - 10.10.252.11:9092
    - 10.10.252.12:9092
    - 10.10.252.13:9092
  hdfs_namenode_rpc: 10.10.252.12:9000
  hdfs_namenode_web: 10.10.252.12:9870
  hive_metastore: 10.10.252.12:9083
  hive_metastore_postgres: 10.10.252.12:5435
  spark_master: spark://10.10.252.12:7077
  spark_master_ui: http://10.10.252.12:8086
  spark_thrift: 10.10.252.12:10000
  trino_coordinator: http://10.10.252.12:8088

execution_model:
  ingestion: kafka_cluster_on_vm1_vm2_vm3
  distributed_storage: hdfs_namenode_on_vm2_with_datanodes_on_vm1_vm2_vm3
  distributed_processing: spark_master_on_vm2_with_workers_on_vm1_vm2_vm3
  distributed_querying: trino_coordinator_on_vm2_with_workers_on_vm1_vm3
  orchestration: airflow_on_local_pc
  transformation_runtime: dbt_on_local_pc_via_remote_spark_thrift
  data_quality_runtime: gx_on_local_pc_against_remote_lakehouse
