coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8088
discovery.uri=http://10.10.252.12:8088
query.max-memory=512MB
query.max-memory-per-node=256MB
query.max-total-memory=768MB
memory.heap-headroom-per-node=128MB
