coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8089
http-server.process-forwarded=true
discovery.uri=http://10.10.252.12:8089
internal-communication.shared-secret=CustomerDNA_Trino_Internal_Shared_Secret_2026
query.max-memory=512MB
query.max-memory-per-node=256MB
query.max-total-memory=768MB
memory.heap-headroom-per-node=128MB
