[libdefaults]
 default_realm = CUSTOMERDNA.LOCAL
 dns_lookup_realm = false
 dns_lookup_kdc = false
 dns_canonicalize_hostname = false
 rdns = false
 ticket_lifetime = 60d
 renew_lifetime = 60d
 forwardable = true
 udp_preference_limit = 1

[realms]
 CUSTOMERDNA.LOCAL = {
  kdc = 10.10.252.12
  admin_server = 10.10.252.12
 }

[domain_realm]
 .customerdna.local = CUSTOMERDNA.LOCAL
 customerdna.local = CUSTOMERDNA.LOCAL
