Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/etc/security/keytabs/spark.service.keytab"
  principal="spark@CUSTOMERDNA.LOCAL"
  useTicketCache=false
  doNotPrompt=true
  storeKey=true
  refreshKrb5Config=true;
};
