select
    sha2(
        concat_ws(
            '||',
            coalesce(cast(administrative as string), ''),
            coalesce(cast(administrative_duration as string), ''),
            coalesce(cast(informational as string), ''),
            coalesce(cast(informational_duration as string), ''),
            coalesce(cast(productrelated as string), ''),
            coalesce(cast(productrelated_duration as string), ''),
            coalesce(cast(bouncerates as string), ''),
            coalesce(cast(exitrates as string), ''),
            coalesce(cast(pagevalues as string), ''),
            coalesce(cast(specialday as string), ''),
            coalesce(month, ''),
            coalesce(cast(operatingsystems as string), ''),
            coalesce(cast(browser as string), ''),
            coalesce(cast(region as string), ''),
            coalesce(cast(traffictype as string), ''),
            coalesce(visitortype, ''),
            coalesce(weekend, ''),
            coalesce(revenue, '')
        ),
        256
    ) as shopper_session_id,
    {{ as_int('administrative') }} as administrative_page_count,
    {{ as_double('administrative_duration') }} as administrative_duration_seconds,
    {{ as_int('informational') }} as informational_page_count,
    {{ as_double('informational_duration') }} as informational_duration_seconds,
    {{ as_int('productrelated') }} as product_related_page_count,
    {{ as_double('productrelated_duration') }} as product_related_duration_seconds,
    {{ as_double('bouncerates') }} as bounce_rate,
    {{ as_double('exitrates') }} as exit_rate,
    {{ as_double('pagevalues') }} as page_value_score,
    {{ as_double('specialday') }} as special_day_score,
    trim(month) as session_month,
    {{ as_int('operatingsystems') }} as operating_system_id,
    {{ as_int('browser') }} as browser_id,
    {{ as_int('region') }} as region_id,
    {{ as_int('traffictype') }} as traffic_type_id,
    trim(visitortype) as visitor_type,
    {{ as_boolean_flag('weekend') }} as is_weekend_session,
    {{ as_boolean_flag('revenue') }} as converted_in_session_flag
from {{ source('raw_data', 'online_shoppers_intention') }}
