#!/usr/bin/env python3
"""
CustomerDNA AI - Client 1 dbt Setup Script

This script helps set up the dbt environment for the project.
It creates the necessary profiles.yml configuration and validates the setup.

Usage:
    python setup_dbt.py
"""

import os
import sys
import shutil
from pathlib import Path

# Add parent directory to path to import config
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "config"))

try:
    from config import (
        CLIENT_ID,
        CLIENT_NAME,
        DATA_WAREHOUSE_NAME,
        POSTGRES_CONFIG,
        CLIENT_DW_CONFIG,
    )
except ImportError:
    print("[ERROR] Could not import project configuration")
    print("Make sure you're running from the correct directory")
    sys.exit(1)


def get_dbt_profiles_path():
    """Get the path to the dbt profiles.yml file."""
    home = Path.home()
    
    # Check for dbt profiles directory
    dbt_dir = home / ".dbt"
    
    # Create directory if it doesn't exist
    dbt_dir.mkdir(exist_ok=True)
    
    return dbt_dir / "profiles.yml"


def create_dbt_profile():
    """Create the dbt profile configuration."""
    
    profile_content = f"""# CustomerDNA AI - {CLIENT_NAME} dbt Profile
# Auto-generated by setup_dbt.py

customerdna_client{CLIENT_ID}:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{POSTGRES_CONFIG['host']}"
      port: {POSTGRES_CONFIG['port']}
      user: "{POSTGRES_CONFIG['user']}"
      pass: "{POSTGRES_CONFIG['password']}"
      dbname: "{DATA_WAREHOUSE_NAME}"
      schema: "staging"
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      
    prod:
      type: postgres
      host: "${{{{ env_var('PROD_POSTGRES_HOST', '{POSTGRES_CONFIG['host']}') }}}}"
      port: "${{{{ env_var('PROD_POSTGRES_PORT', {POSTGRES_CONFIG['port']}) }}}}"
      user: "${{{{ env_var('PROD_POSTGRES_USER', '{POSTGRES_CONFIG['user']}') }}}}"
      pass: "${{{{ env_var('PROD_POSTGRES_PASSWORD', '{POSTGRES_CONFIG['password']}') }}}}"
      dbname: "{DATA_WAREHOUSE_NAME}"
      schema: "analytics"
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3
      
    test:
      type: postgres
      host: "{POSTGRES_CONFIG['host']}"
      port: {POSTGRES_CONFIG['port']}
      user: "{POSTGRES_CONFIG['user']}"
      pass: "{POSTGRES_CONFIG['password']}"
      dbname: "{DATA_WAREHOUSE_NAME}"
      schema: "test"
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
"""
    
    return profile_content


def backup_existing_profile(profile_path):
    """Backup existing profiles.yml if it exists."""
    if profile_path.exists():
        backup_path = profile_path.with_suffix('.yml.backup')
        shutil.copy2(profile_path, backup_path)
        print(f"[INFO] Backed up existing profile to: {backup_path}")
        return True
    return False


def main():
    """Main setup function."""
    
    print("=" * 60)
    print(f"CUSTOMERDNA AI - {CLIENT_NAME} DBT SETUP")
    print("=" * 60)
    
    # Get profiles path
    profiles_path = get_dbt_profiles_path()
    print(f"[INFO] DBT profiles location: {profiles_path}")
    
    # Backup existing profile
    backup_existing_profile(profiles_path)
    
    # Create new profile content
    profile_content = create_dbt_profile()
    
    # Write profile
    try:
        with open(profiles_path, 'w') as f:
            f.write(profile_content)
        print(f"[SUCCESS] Created dbt profile at: {profiles_path}")
    except Exception as e:
        print(f"[ERROR] Failed to write profile: {str(e)}")
        sys.exit(1)
    
    # Display configuration summary
    print("\n" + "=" * 60)
    print("CONFIGURATION SUMMARY")
    print("=" * 60)
    print(f"Client ID: {CLIENT_ID}")
    print(f"Client Name: {CLIENT_NAME}")
    print(f"Database: {DATA_WAREHOUSE_NAME}")
    print(f"Host: {POSTGRES_CONFIG['host']}:{POSTGRES_CONFIG['port']}")
    print(f"User: {POSTGRES_CONFIG['user']}")
    
    print("\nSchemas configured:")
    for schema in CLIENT_DW_CONFIG['schemas']:
        print(f"  - {schema}")
    
    print("\n" + "=" * 60)
    print("NEXT STEPS")
    print("=" * 60)
    print("1. Verify dbt installation:")
    print("   dbt --version")
    print("\n2. Test connection to database:")
    print("   dbt debug")
    print("\n3. Run dbt models:")
    print("   dbt run")
    print("\n4. Test data quality:")
    print("   dbt test")
    print("\n5. Generate documentation:")
    print("   dbt docs generate")
    print("   dbt docs serve")
    
    print("\n" + "=" * 60)
    print("PROJECT STRUCTURE")
    print("=" * 60)
    print("dbt/")
    print("├── models/")
    print("│   ├── staging/     # Clean raw data")
    print("│   ├── intermediate/# Business transformations")
    print("│   └── analytics/   # Final reporting tables")
    print("├── dbt_project.yml  # Project configuration")
    print("└── profiles.yml     # Database connections (template)")
    
    print("\n[SUCCESS] dbt setup completed!")


if __name__ == "__main__":
    main()