Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/etc/security/keytabs/spark.service.keytab"
  principal="spark@CUSTOMERDNA.LOCAL"
  useTicketCache=true
  renewTGT=true
  doNotPrompt=true
  storeKey=true
  refreshKrb5Config=true
  isInitiator=true;
};

com.sun.security.jgss.initiate {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/etc/security/keytabs/spark.service.keytab"
  principal="spark@CUSTOMERDNA.LOCAL"
  useTicketCache=true
  renewTGT=true
  doNotPrompt=true
  storeKey=true
  refreshKrb5Config=true
  isInitiator=true;
};

com.sun.security.jgss.krb5.initiate {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  keyTab="/etc/security/keytabs/spark.service.keytab"
  principal="spark@CUSTOMERDNA.LOCAL"
  useTicketCache=true
  renewTGT=true
  doNotPrompt=true
  storeKey=true
  refreshKrb5Config=true
  isInitiator=true;
};
