spark.eventLog.enabled                       true
spark.eventLog.dir                           file:/tmp/spark-events
spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog                     customerdna
spark.sql.catalog.customerdna                org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.customerdna.type           hive
spark.sql.catalog.customerdna.uri            thrift://hive-metastore:9083
spark.sql.catalog.customerdna.warehouse      hdfs://namenode:9000/warehouse/iceberg
spark.sql.catalog.customerdna.cache-enabled  false
spark.sql.catalog.customerdna.iceberg.engine.hive.lock-enabled false
spark.sql.artifact.isolation.enabled         false
spark.driver.extraClassPath                  /opt/spark/jars/iceberg-spark-runtime-4.1_2.13-1.11.0.jar:/opt/spark/jars/postgresql-42.7.4.jar
spark.executor.extraClassPath                /opt/spark/jars/iceberg-spark-runtime-4.1_2.13-1.11.0.jar:/opt/spark/jars/postgresql-42.7.4.jar
spark.hadoop.hive.metastore.uris             thrift://hive-metastore:9083
spark.kerberos.principal                     spark@CUSTOMERDNA.LOCAL
spark.kerberos.keytab                        /etc/security/keytabs/spark.service.keytab
spark.kerberos.access.hadoopFileSystems      hdfs://namenode:9000
spark.sql.sources.partitionOverwriteMode     dynamic
spark.sql.adaptive.enabled                   true
