spark.eventLog.enabled                       true
spark.eventLog.dir                           file:/tmp/spark-events
spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog                     customerdna
spark.sql.catalog.customerdna                org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.customerdna.type           hive
spark.sql.catalog.customerdna.uri            thrift://10.10.252.12:9083
spark.sql.catalog.customerdna.warehouse      hdfs://namenode.customerdna.local:9000/warehouse/iceberg
spark.sql.catalog.customerdna.cache-enabled  false
spark.sql.artifact.isolation.enabled         false
spark.driver.extraClassPath                  /opt/spark/jars/iceberg-spark-runtime-4.1_2.13-1.11.0.jar:/opt/spark/jars/postgresql-42.7.4.jar
spark.executor.extraClassPath                /opt/spark/jars/iceberg-spark-runtime-4.1_2.13-1.11.0.jar:/opt/spark/jars/postgresql-42.7.4.jar
spark.driver.extraJavaOptions                -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false
spark.executor.extraJavaOptions              -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false
spark.driverEnv.KRB5_CONFIG                  /etc/krb5.conf
spark.driverEnv.KRB5CCNAME                   FILE:/tmp/krb5cc_spark
spark.executorEnv.KRB5_CONFIG                /etc/krb5.conf
spark.executorEnv.KRB5CCNAME                 FILE:/tmp/krb5cc_spark
spark.kerberos.principal                     spark@CUSTOMERDNA.LOCAL
spark.kerberos.keytab                        /etc/security/keytabs/spark.service.keytab
spark.hadoop.hive.metastore.uris             thrift://10.10.252.12:9083
spark.hadoop.fs.defaultFS                    hdfs://namenode.customerdna.local:9000
spark.hadoop.hadoop.security.authentication  kerberos
spark.hadoop.hadoop.security.authorization   true
spark.hadoop.hadoop.rpc.protection           privacy
spark.hadoop.dfs.namenode.kerberos.principal nn/namenode.customerdna.local@CUSTOMERDNA.LOCAL
spark.hadoop.dfs.data.transfer.protection    privacy
spark.hadoop.dfs.encrypt.data.transfer       true
spark.hadoop.dfs.client.use.datanode.hostname true
spark.kerberos.renewal.credentials           ccache
spark.sql.sources.partitionOverwriteMode     dynamic
spark.sql.adaptive.enabled                   true
