customerdna_client1_lakehouse:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('CUSTOMERDNA_DBT_SPARK_HOST', 'localhost') }}"
      port: "{{ env_var('CUSTOMERDNA_DBT_SPARK_PORT', '10000') | as_number }}"
      user: "{{ env_var('CUSTOMERDNA_DBT_SPARK_USER', 'dbt') }}"
      schema: raw_data
      threads: 4
      auth: NONE
      connect_timeout: 60
      connect_retries: 5
      retry_all: true
